### ISSUE TITLE
VOLTE on Openstack

### ISSUE THREAD

**Issue by ghost** [herlesupreeth/Kamailio_IMS_Config#9]
Dear @herlesupreeth 
Hi again

I managed to run IMS+Core on Openstack with internal ip 10.4.128.21/24 and Floating Ip address of 10.20.20.177 which both of them are on a Single PC with 192.168.100.20 ip addresses. and installed SRSLTE on the other PC with ip address of 192.168.100.2 so now eNB is connected to MME and UE registered on the network. 
But i do not have internet access!
I have done these to be able to connect eNB to Core :
`sudo route add -net 10.20.20.0/24 gw 192.168.100.20 enp1s0
`
and Now i tried your command:
`ip r add 10.4.128.21/24 via 10.20.20.177`
but it says: 

> ERROR: INVALID prefix for given prefix length.

and I dont have internet access!!

and Also Tested SRSEPC commands  sudo srsepc_if_masq enp1s0

But still not access!

also in sgw:
```
sgw:
    gtpc:
      addr: 127.0.0.2
    gtpu:
      dev: ens3
      advertise_addr: 10.20.20.177

```
i had set advertise_addr!
Can u please give me a hint?

Thanks 
Best regards

P.S.    I set UE's pool in  pgw.yaml
```
 ue_pool:
      - addr: 172.20.110.1/24
        dev: ogstun
        apn: internet
      - addr: 172.20.111.1/24
        apn: ims
        dev: ogstun2
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
    p-cscf:
      - 10.4.128.21

```
